/*CREATE USER VEM_SER IDENTIFIED BY oracle;
GRANT CONNECT TO VEM_SER;
GRANT CONNECT, RESOURCE, DBA TO VEM_SER;
GRANT CREATE SESSION TO VEM_SER;
GRANT DBA TO VEM_SER;
GRANT CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE to VEM_SER;
GRANT UNLIMITED TABLESPACE TO VEM_SER;
GRANT CREATE MATERIALIZED VIEW TO VEM_SER;
GRANT CREATE TABLE TO VEM_SER;
GRANT GLOBAL QUERY REWRITE TO VEM_SER;
GRANT SELECT ANY TABLE TO VEM_SER;
*/

/*CREATE TABLE VEM_SER.PESSOA(
	id_pessoa NUMBER NOT NULL,
	nome VARCHAR2(255) NOT NULL,
	data_nascimento DATE NOT NULL,
	telefone VARCHAR2(14), --+551995249346
	idade NUMBER(3) NOT NULL,
	altura DECIMAL(4,2) NOT NULL,
	cpf CHAR(11) UNIQUE NOT NULL,
	PRIMARY KEY(id_pessoa)
);*/

--DROP TABLE VEM_SER.PESSOA; --comandinho do mau, mata tudo

/*CREATE SEQUENCE VEM_SER.seq_pessoa
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;*/

/*DROP SEQUENCE VEM_SER.seq_pessoa*/

SELECT * FROM VEM_SER.PESSOA;

--SELECT ID_PESSOA, CPF, NOME FROM VEM_SER.PESSOA;

/*SELECT ID_PESSOA
	, CPF || ' - ' ||NOME AS "CPF - NOME" 
FROM VEM_SER.PESSOA;*/

/*INSERT INTO VEM_SER.PESSOA (ID_PESSOA, NOME, DATA_NASCIMENTO, TELEFONE, IDADE, ALTURA, CPF)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Maicon Machado Gerardi', TO_DATE('08-09-1991', 'dd-mm-yyyy'), '519958654566', 30, 1.75, '50799501026');*/

/*INSERT INTO VEM_SER.PESSOA (ID_PESSOA, NOME, DATA_NASCIMENTO, IDADE, ALTURA, CPF)
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Maicon Machado Gerardi2', TO_DATE('08-09-1991', 'dd-mm-yyyy'), 30, 1.75, '50799501027');*/

/*INSERT INTO VEM_SER.PESSOA
VALUES(VEM_SER.SEQ_PESSOA.nextval, 'Maicon Machado Gerardi', TO_DATE('08-09-1991', 'dd-mm-yyyy'), '519958654566', 30, 1.75, '50799501028');*/