UPDATE VEM_SER.CIDADE
SET NOME = CONCAT('RUA ',NOME)
WHERE NOME NOT LIKE 'RUA%';

SELECT * FROM VEM_SER.CIDADE;

UPDATE VEM_SER.CIDADE
SET NOME = REPLACE(NOME,'RUA ','')
WHERE NOME LIKE 'RUA %';

DELETE FROM VEM_SER.ENDERECO WHERE LOGRADOURO LIKE 'NAOVAIACHARKKKK';


SELECT * FROM VEM_SER.ENDERECO;
--EXERCICIO1
UPDATE VEM_SER.ENDERECO
SET LOGRADOURO = CONCAT(LOGRADOURO,' :OK_HAND:'),
COMPLEMENTO = ''
WHERE ID_ENDERECO = 2 OR ID_ENDERECO = 3;

UPDATE VEM_SER.ENDERECO
SET NUMERO = 999999
WHERE ID_ENDERECO = 4;

DELETE FROM VEM_SER.ENDERECO
WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM VEM_SER.ENDERECO);

DELETE FROM VEM_SER.ENDERECO
WHERE NUMERO = 999999;

DELETE FROM VEM_SER.ENDERECO;

/*DROP SEQUENCE VEM_SER.SEQ_ESTUDANTE;
DROP SEQUENCE VEM_SER.SEQ_PESSOA;*/

/*DROP TABLE VEM_SER.PESSOA;
DROP TABLE VEM_SER.ESTUDANTE;*/


--EXERCICIO2
SELECT VEM_SER.PESSOA.NOME, VEM_SER.CONTATO.NUMERO
FROM VEM_SER.PESSOA
CROSS JOIN VEM_SER.CONTATO;

SELECT VEM_SER.PESSOA.NOME, VEM_SER.CONTATO.NUMERO
FROM VEM_SER.PESSOA
INNER JOIN VEM_SER.CONTATO ON (VEM_SER.PESSOA.ID_PESSOA = VEM_SER.CONTATO.ID_PESSOA);

SELECT p.NOME, ep.LOGRADOURO
FROM VEM_SER.PESSOA p
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	ON p.ID_PESSOA = pxpe.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA ep
	ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;
	
SELECT p.NOME, ep.LOGRADOURO, c.NUMERO
FROM VEM_SER.PESSOA p
INNER JOIN VEM_SER.CONTATO c
	ON p.ID_PESSOA = c.ID_PESSOA
INNER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	ON p.ID_PESSOA = pxpe.ID_PESSOA
INNER JOIN VEM_SER.ENDERECO_PESSOA ep
	ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;


SELECT p.NOME, c.NUMERO
FROM VEM_SER.PESSOA p
LEFT JOIN VEM_SER.CONTATO c ON (p.ID_PESSOA = c.ID_PESSOA);

SELECT p.NOME, ep.LOGRADOURO
FROM VEM_SER.PESSOA p
LEFT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	ON p.ID_PESSOA = pxpe.ID_PESSOA
LEFT JOIN VEM_SER.ENDERECO_PESSOA ep
	ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;
	
SELECT * --p.NOME, ep.LOGRADOURO, c.NUMERO
FROM VEM_SER.PESSOA p
LEFT JOIN VEM_SER.CONTATO c
	ON p.ID_PESSOA = c.ID_PESSOA
LEFT JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	ON p.ID_PESSOA = pxpe.ID_PESSOA
LEFT JOIN VEM_SER.ENDERECO_PESSOA ep
	ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;
	

/*--TESTE DE FULL OUTER
SELECT p.NOME, ep.LOGRADOURO, c.NUMERO
FROM VEM_SER.PESSOA p
FULL OUTER JOIN VEM_SER.CONTATO c
	ON p.ID_PESSOA = c.ID_PESSOA
FULL OUTER JOIN VEM_SER.PESSOA_X_PESSOA_ENDERECO pxpe
	ON p.ID_PESSOA = pxpe.ID_PESSOA
FULL OUTER JOIN VEM_SER.ENDERECO_PESSOA ep
	ON pxpe.ID_ENDERECO = ep.ID_ENDERECO;*/